package dev.arcn.craftstudio.graph.domain;

public enum GraphEdgeType {
	HAS_BLOCKSTATE,
	HAS_CLIENT_ITEM,
	SELECTS_MODEL,
	USES_MODEL,
	INHERITS_MODEL,
	USES_TEXTURE_VARIABLE,
	RESOLVES_TEXTURE,
	USES_METADATA,
	REQUIRES_ATLAS,
	SHARED_BY,
	HAS_VARIANT,
	HAS_MULTIPART_CASE,
	USES_SPECIAL_RENDERER
}
